#!/usr/bin/env bash
# Script that transfers a file from our client to a server

if [ $# -ge 3 ]
then
    if [ $# -eq 3 ]
    then
        #if no private key is provided
        scp -o StrictHostKeyChecking=no $1 $3@$2:~/ 
    else
        #  if Private key is provided
        scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
    fi
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
